version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    networks:
      - malaka-net

  api:
    build: .
    container_name: go-api
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST}
    networks:
      - malaka-net

networks:
  malaka-net:
    driver: bridge
